### ISSUE TITLE
Timers are not deleted with board teardown

### ISSUE THREAD

**Issue by bgromov** [mbientlab/MetaWear-SDK-Python#12]
**Model**: MetaMotion R
**Model Number**: 5
**Firmware**: 1.4.4
**Hardware**: 0.3
**Python SDK version**: 0.7.0

Every call to `mbl_mw_timer_create()` creates a timer with incremented ID even after a teardown of the board. This way timer IDs are quickly exhausted and after 8th (ID 7) the timer create callback returns `None`.

The problem could actually be only with the IDs counter as the timers themselves do not exist: at least `mbl_mw_timer_lookup_id()` could not find timers with the IDs created before teardown.

Removing a timer works fine, i.e. next call to `mbl_mw_timer_create()` creates a timer with an ID of the previously deleted one.

**Comment by scaryghost** [comment]
Post a code snippet that reliable reproduces this behavior.

**Comment by bgromov** [comment]
Here you are:

```python
# usage: python timer_bug.py [mac]
from __future__ import print_function
from mbientlab.metawear import MetaWear, libmetawear, create_voidp
from mbientlab.metawear.cbindings import *
from threading import Event
import time

import sys

for i in range(1, 10):
    print('Attempt: {}'.format(i))

    device = MetaWear(sys.argv[1])
    device.connect()
    print('\tConnected to ' + device.address)

    e = Event()

    print('\tTearing down device')
    libmetawear.mbl_mw_metawearboard_tear_down(device.board)

    print('\tConfiguring device')
    timer = create_voidp(lambda fn: libmetawear.mbl_mw_timer_create(device.board, 300, 1, 0, None, fn), resource = 'timer')
    print('\tTimer {} created'.format(libmetawear.mbl_mw_timer_get_id(timer)))

    print('\tDisconnecting from device')
    device.on_disconnect = lambda status: e.set()
    device.disconnect()
    e.wait()
    print('\tDisconnected')
```

The output:

```
Attempt: 1
	Connected to aa:bb:cc:dd:ee:ff
	Tearing down device
	Configuring device
	Timer 0 created
	Disconnecting from device
	Disconnected
Attempt: 2
	Connected to aa:bb:cc:dd:ee:ff
	Tearing down device
	Configuring device
	Timer 1 created
	Disconnecting from device
	Disconnected
Attempt: 3
	Connected to aa:bb:cc:dd:ee:ff
	Tearing down device
	Configuring device
	Timer 2 created
	Disconnecting from device
	Disconnected
Attempt: 4
	Connected to aa:bb:cc:dd:ee:ff
	Tearing down device
	Configuring device
	Timer 3 created
	Disconnecting from device
	Disconnected
Attempt: 5
	Connected to aa:bb:cc:dd:ee:ff
	Tearing down device
	Configuring device
	Timer 4 created
	Disconnecting from device
	Disconnected
Attempt: 6
	Connected to aa:bb:cc:dd:ee:ff
	Tearing down device
	Configuring device
	Timer 5 created
	Disconnecting from device
	Disconnected
Attempt: 7
	Connected to aa:bb:cc:dd:ee:ff
	Tearing down device
	Configuring device
	Timer 6 created
	Disconnecting from device
	Disconnected
Attempt: 8
	Connected to aa:bb:cc:dd:ee:ff
	Tearing down device
	Configuring device
	Timer 7 created
	Disconnecting from device
	Disconnected
Attempt: 9
	Connected to aa:bb:cc:dd:ee:ff
	Tearing down device
	Configuring device
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/Users/0xff/.virtualenvs/py2/lib/python2.7/site-packages/mbientlab/metawear/__init__.py", line 76, in handler
    result[0] = RuntimeError("Could not create " + (resource if 'resource' in kwarg else "resource") ) if pointer == None else pointer
NameError: global name 'kwarg' is not defined
Killed: 9
```

Note though, it happens only if I disconnect from the device, if I run `tear_down` and `timer_create` inside a loop, everything is fine.

**Comment by scaryghost** [comment]
Tear down only removes timers it is aware of.  Since the MetaWear object does not live outside the loop, its not preserving the internal timer objects.  

Either serialize the object or just reset the board.
