### ISSUE TITLE
pip install fails?

### ISSUE THREAD

**Issue by cryoguy** [mbientlab/MetaWear-SDK-Python#18]
`pip install metawear` spits out the following, any suggestions?

```
Collecting metawear
  Using cached metawear-0.7.0.tar.gz (330 kB)
Requirement already satisfied: warble<2.0,>=1.1 in /usr/lib/python3.9/site-packages (from metawear) (1.2.0)
Requirement already satisfied: requests in /usr/lib/python3.9/site-packages (from metawear) (2.25.0)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.9/site-packages (from requests->metawear) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.9/site-packages (from requests->metawear) (2.10)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.9/site-packages (from requests->metawear) (1.25.10)
Building wheels for collected packages: metawear
  Building wheel for metawear (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-42n0e7na/metawear/setup.py'"'"'; __file__='"'"'/tmp/pip-install-42n0e7na/metawear/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bixy1owl
       cwd: /tmp/pip-install-42n0e7na/metawear/
  Complete output (75 lines):
  running bdist_wheel
  running build
  running build_py
  make: Entering directory '/tmp/pip-install-42n0e7na/metawear/MetaWear-SDK-Cpp'
  mkdir -p build/x64/release/src/metawear/platform/cpp
  mkdir -p build/x64/release/src/metawear/core/cpp
  mkdir -p build/x64/release/src/metawear/peripheral/cpp
  mkdir -p build/x64/release/src/metawear/processor/cpp
  mkdir -p build/x64/release/src/metawear/sensor/cpp
  mkdir -p build/x64/release/src/metawear/impl/cpp
  mkdir -p build/x64/release/src/metawear/dfu/cpp
  mkdir -p dist/release/lib/x64
  g++ -MMD -MP -MF "build/x64/release/src/metawear/platform/cpp/threadpool.d" -c -o build/x64/release/src/metawear/platform/cpp/threadpool.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/platform/cpp/threadpool.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/platform/cpp/task.d" -c -o build/x64/release/src/metawear/platform/cpp/task.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/platform/cpp/task.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/platform/cpp/memory.d" -c -o build/x64/release/src/metawear/platform/cpp/memory.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/platform/cpp/memory.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/platform/cpp/async_creator.d" -c -o build/x64/release/src/metawear/platform/cpp/async_creator.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/platform/cpp/async_creator.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/core/cpp/version.d" -c -o build/x64/release/src/metawear/core/cpp/version.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/core/cpp/version.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/core/cpp/timer.d" -c -o build/x64/release/src/metawear/core/cpp/timer.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/core/cpp/timer.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/core/cpp/settings.d" -c -o build/x64/release/src/metawear/core/cpp/settings.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/core/cpp/settings.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/core/cpp/responseheader.d" -c -o build/x64/release/src/metawear/core/cpp/responseheader.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/core/cpp/responseheader.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/core/cpp/moduleinfo.d" -c -o build/x64/release/src/metawear/core/cpp/moduleinfo.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/core/cpp/moduleinfo.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/core/cpp/macro.d" -c -o build/x64/release/src/metawear/core/cpp/macro.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/core/cpp/macro.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/core/cpp/logging.d" -c -o build/x64/release/src/metawear/core/cpp/logging.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/core/cpp/logging.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/core/cpp/event.d" -c -o build/x64/release/src/metawear/core/cpp/event.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/core/cpp/event.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/core/cpp/debug.d" -c -o build/x64/release/src/metawear/core/cpp/debug.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/core/cpp/debug.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/core/cpp/datasignal.d" -c -o build/x64/release/src/metawear/core/cpp/datasignal.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/core/cpp/datasignal.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/core/cpp/anonymous_datasignal.d" -c -o build/x64/release/src/metawear/core/cpp/anonymous_datasignal.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/core/cpp/anonymous_datasignal.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/peripheral/cpp/neopixel.d" -c -o build/x64/release/src/metawear/peripheral/cpp/neopixel.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/peripheral/cpp/neopixel.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/peripheral/cpp/led.d" -c -o build/x64/release/src/metawear/peripheral/cpp/led.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/peripheral/cpp/led.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/peripheral/cpp/ibeacon.d" -c -o build/x64/release/src/metawear/peripheral/cpp/ibeacon.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/peripheral/cpp/ibeacon.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/peripheral/cpp/haptic.d" -c -o build/x64/release/src/metawear/peripheral/cpp/haptic.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/peripheral/cpp/haptic.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/processor/cpp/dataprocessor_config.d" -c -o build/x64/release/src/metawear/processor/cpp/dataprocessor_config.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/processor/cpp/dataprocessor_config.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/processor/cpp/dataprocessor.d" -c -o build/x64/release/src/metawear/processor/cpp/dataprocessor.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/processor/cpp/dataprocessor.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/utils.d" -c -o build/x64/release/src/metawear/sensor/cpp/utils.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/utils.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/switch.d" -c -o build/x64/release/src/metawear/sensor/cpp/switch.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/switch.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/serialpassthrough.d" -c -o build/x64/release/src/metawear/sensor/cpp/serialpassthrough.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/serialpassthrough.cpp
  g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/sensor_fusion.d" -c -o build/x64/release/src/metawear/sensor/cpp/sensor_fusion.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/sensor_fusion.cpp
  src/metawear/sensor/cpp/utils.cpp: In function ‘char* copy_string(const char*)’:
  src/metawear/sensor/cpp/utils.cpp:26:11: error: ‘char* strcpy(char*, const char*)’ writing one too many bytes into a region of a size that depends on ‘strlen’ [-Werror=stringop-overflow=]
     26 |     strcpy(buffer, src);
        |     ~~~~~~^~~~~~~~~~~~~
  src/metawear/sensor/cpp/utils.cpp:25:38: note: at offset 0 to an object allocated by ‘malloc’ here
     25 |     char* buffer = (char*)std::malloc(strlen(src));
        |                           ~~~~~~~~~~~^~~~~~~~~~~~~
  cc1plus: all warnings being treated as errors
  make: *** [Makefile:69: build/x64/release/src/metawear/sensor/cpp/utils.o] Error 1
  make: *** Waiting for unfinished jobs....
  make: Leaving directory '/tmp/pip-install-42n0e7na/metawear/MetaWear-SDK-Cpp'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-42n0e7na/metawear/setup.py", line 66, in <module>
      setup(
    File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-42n0e7na/metawear/setup.py", line 56, in run
      raise RuntimeError("Failed to compile C++ SDK")
  RuntimeError: Failed to compile C++ SDK
  ----------------------------------------
  ERROR: Failed building wheel for metawear
  Running setup.py clean for metawear
Failed to build metawear
DEPRECATION: Could not build wheels for metawear which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: metawear
    Running setup.py install for metawear ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-42n0e7na/metawear/setup.py'"'"'; __file__='"'"'/tmp/pip-install-42n0e7na/metawear/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-d_53s6lh/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/metawear
         cwd: /tmp/pip-install-42n0e7na/metawear/
    Complete output (52 lines):
    running install
    running build
    running build_py
    make: Entering directory '/tmp/pip-install-42n0e7na/metawear/MetaWear-SDK-Cpp'
    g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/utils.d" -c -o build/x64/release/src/metawear/sensor/cpp/utils.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/utils.cpp
    g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/proximity_tsl2671.d" -c -o build/x64/release/src/metawear/sensor/cpp/proximity_tsl2671.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/proximity_tsl2671.cpp
    g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/multichanneltemperature.d" -c -o build/x64/release/src/metawear/sensor/cpp/multichanneltemperature.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/multichanneltemperature.cpp
    g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/magnetometer_bmm150.d" -c -o build/x64/release/src/metawear/sensor/cpp/magnetometer_bmm150.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/magnetometer_bmm150.cpp
    g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/humidity_bme280.d" -c -o build/x64/release/src/metawear/sensor/cpp/humidity_bme280.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/humidity_bme280.cpp
    g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/gyro_bmi160.d" -c -o build/x64/release/src/metawear/sensor/cpp/gyro_bmi160.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/gyro_bmi160.cpp
    g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/gpio.d" -c -o build/x64/release/src/metawear/sensor/cpp/gpio.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/gpio.cpp
    g++ -MMD -MP -MF "build/x64/release/src/metawear/sensor/cpp/conductance.d" -c -o build/x64/release/src/metawear/sensor/cpp/conductance.o -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -Isrc -DMETAWEAR_DLL -DMETAWEAR_DLL_EXPORTS -Wno-strict-aliasing -O3 -m64 src/metawear/sensor/cpp/conductance.cpp
    src/metawear/sensor/cpp/utils.cpp: In function ‘char* copy_string(const char*)’:
    src/metawear/sensor/cpp/utils.cpp:26:11: error: ‘char* strcpy(char*, const char*)’ writing one too many bytes into a region of a size that depends on ‘strlen’ [-Werror=stringop-overflow=]
       26 |     strcpy(buffer, src);
          |     ~~~~~~^~~~~~~~~~~~~
    src/metawear/sensor/cpp/utils.cpp:25:38: note: at offset 0 to an object allocated by ‘malloc’ here
       25 |     char* buffer = (char*)std::malloc(strlen(src));
          |                           ~~~~~~~~~~~^~~~~~~~~~~~~
    cc1plus: all warnings being treated as errors
    make: *** [Makefile:69: build/x64/release/src/metawear/sensor/cpp/utils.o] Error 1
    make: *** Waiting for unfinished jobs....
    make: Leaving directory '/tmp/pip-install-42n0e7na/metawear/MetaWear-SDK-Cpp'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-42n0e7na/metawear/setup.py", line 66, in <module>
        setup(
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-42n0e7na/metawear/setup.py", line 56, in run
        raise RuntimeError("Failed to compile C++ SDK")
    RuntimeError: Failed to compile C++ SDK
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-42n0e7na/metawear/setup.py'"'"'; __file__='"'"'/tmp/pip-install-42n0e7na/metawear/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-d_53s6lh/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/metawear Check the logs for full command output.

```

**Comment by lkasso** [comment]
This has been fixed in the latest CPP.
Git update the submodules and make from the SDK folder.
Will update this repo momentarily.
