### ISSUE TITLE
Error while installing using pip 

### ISSUE THREAD

**Issue by mamdouhJ** [mbientlab/MetaWear-SDK-Python#22]
I followed through the tutorial for installing on windows. I used pip to install metawear but got the fllowing error: 

`Defaulting to user installation because normal site-packages is not writeable
Collecting metawear
  Using cached metawear-1.0.2.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
Collecting warble<2.0,>=1.1
  Using cached warble-1.2.6.tar.gz (1.6 MB)
  Preparing metadata (setup.py) ... done
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages (from requests->metawear) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages (from requests->metawear) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages (from requests->metawear) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages (from requests->metawear) (2021.10.8)
Using legacy 'setup.py install' for metawear, since package 'wheel' is not installed.
Using legacy 'setup.py install' for warble, since package 'wheel' is not installed.
Installing collected packages: warble, requests, metawear
    Running setup.py install for warble ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\microsoft visual studio\shared\python36_64\python3.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mamdo\\AppData\\Local\\Temp\\pip-install-alsb0eb9\\warble_5505a598e72246b6a90908d31403bc5b\\setup.py'"'"'; __file__='"'"'C:\\Users\\mamdo\\AppData\\Local\\Temp\\pip-install-alsb0eb9\\warble_5505a598e72246b6a90908d31403bc5b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mamdo\AppData\Local\Temp\pip-record-6vasvmxi\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\mamdo\AppData\Roaming\Python\Python36\Include\warble'
         cwd: C:\Users\mamdo\AppData\Local\Temp\pip-install-alsb0eb9\warble_5505a598e72246b6a90908d31403bc5b\
    Complete output (32 lines):
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mamdo\AppData\Local\Temp\pip-install-alsb0eb9\warble_5505a598e72246b6a90908d31403bc5b\setup.py", line 96, in <module>
        'Programming Language :: Python :: 3',
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\mamdo\AppData\Local\Temp\pip-install-alsb0eb9\warble_5505a598e72246b6a90908d31403bc5b\setup.py", line 70, in run
        raise RuntimeError("pywarble is not supported for the '%s' platform" % platform.system())
    RuntimeError: pywarble is not supported for the 'Windows' platform
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files (x86)\microsoft visual studio\shared\python36_64\python3.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mamdo\\AppData\\Local\\Temp\\pip-install-alsb0eb9\\warble_5505a598e72246b6a90908d31403bc5b\\setup.py'"'"'; __file__='"'"'C:\\Users\\mamdo\\AppData\\Local\\Temp\\pip-install-alsb0eb9\\warble_5505a598e72246b6a90908d31403bc5b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mamdo\AppData\Local\Temp\pip-record-6vasvmxi\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\mamdo\AppData\Roaming\Python\Python36\Include\warble' Check the logs for full command output.`

any help would be appreciated.

**Comment by mamdouhJ** [comment]
I also got this error while trying to install mbientlab on a conda environment on ubuntu VM. 

` Building wheel for warble (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/mamdouh/miniconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-sfzp4vd3
       cwd: /tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/
  Complete output (47 lines):
  running bdist_wheel
  running build
  running build_py
  INFO:root:Compiling Warble C++ SDK for Linux (args = ['make', '-C', '/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/clibs/warble', '-j1', 'SKIP_VERSION=1'], cwd = /tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6)
  make: Entering directory '/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/clibs/warble'
  mkdir -p build/x64/release/src/warble/cpp
  g++ -MMD -MP -MF "build/x64/release/src/warble/cpp/lib.d" -c -o build/x64/release/src/warble/cpp/lib.o -std=c++14 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -DWARBLE_DLL -DWARBLE_DLL_EXPORT -Isrc  -O3 -DAPI_BLEPP -Ideps/libblepp  src/warble/cpp/lib.cpp
  In file included from deps/libblepp/blepp/att.h:47,
                   from deps/libblepp/blepp/att_pdu.h:44,
                   from deps/libblepp/blepp/bledevice.h:29,
                   from deps/libblepp/blepp/blestatemachine.h:30,
                   from src/warble/cpp/lib.cpp:9:
  deps/libblepp/blepp/uuid.h:29:10: fatal error: bluetooth/bluetooth.h: No such file or directory
     29 | #include <bluetooth/bluetooth.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  make: *** [Makefile:84: build/x64/release/src/warble/cpp/lib.o] Error 1
  make: Leaving directory '/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/clibs/warble'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py", line 96, in <module>
      'Programming Language :: Python :: 3',
    File "/home/mamdouh/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/mamdouh/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/mamdouh/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/mamdouh/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/mamdouh/miniconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/mamdouh/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/mamdouh/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/mamdouh/miniconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/mamdouh/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/mamdouh/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py", line 63, in run
      root=root
    File "/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py", line 25, in _execute
      raise RuntimeError(kwargs["error_msg"])
  RuntimeError: Failed to compile libwarble.so
  ----------------------------------------
  ERROR: Failed building wheel for warble
  Running setup.py clean for warble
Successfully built metawear
Failed to build warble
Installing collected packages: warble, metawear
    Running setup.py install for warble ... error
    ERROR: Command errored out with exit status 1:
     command: /home/mamdouh/miniconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bf1sq3rz/install-record.txt --single-version-externally-managed --compile --install-headers /home/mamdouh/miniconda3/include/python3.7m/warble
         cwd: /tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/
    Complete output (48 lines):
    running install
    running build
    running build_py
    INFO:root:Compiling Warble C++ SDK for Linux (args = ['make', '-C', '/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/clibs/warble', '-j1', 'SKIP_VERSION=1'], cwd = /tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6)
    make: Entering directory '/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/clibs/warble'
    g++ -MMD -MP -MF "build/x64/release/src/warble/cpp/lib.d" -c -o build/x64/release/src/warble/cpp/lib.o -std=c++14 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Werror -DWARBLE_DLL -DWARBLE_DLL_EXPORT -Isrc  -O3 -DAPI_BLEPP -Ideps/libblepp  src/warble/cpp/lib.cpp
    In file included from deps/libblepp/blepp/att.h:47,
                     from deps/libblepp/blepp/att_pdu.h:44,
                     from deps/libblepp/blepp/bledevice.h:29,
                     from deps/libblepp/blepp/blestatemachine.h:30,
                     from src/warble/cpp/lib.cpp:9:
    deps/libblepp/blepp/uuid.h:29:10: fatal error: bluetooth/bluetooth.h: No such file or directory
       29 | #include <bluetooth/bluetooth.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    make: *** [Makefile:84: build/x64/release/src/warble/cpp/lib.o] Error 1
    make: Leaving directory '/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/clibs/warble'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py", line 96, in <module>
        'Programming Language :: Python :: 3',
      File "/home/mamdouh/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/mamdouh/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/mamdouh/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/mamdouh/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/mamdouh/miniconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/mamdouh/miniconda3/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/mamdouh/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/mamdouh/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/mamdouh/miniconda3/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/mamdouh/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/mamdouh/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py", line 63, in run
        root=root
      File "/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py", line 25, in _execute
        raise RuntimeError(kwargs["error_msg"])
    RuntimeError: Failed to compile libwarble.so
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/mamdouh/miniconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c_qjehff/warble_dd7d14c3d0054783baa77a3ebd3912c6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bf1sq3rz/install-record.txt --single-version-externally-managed --compile --install-headers /home/mamdouh/miniconda3/include/python3.7m/warble Check the logs for full command output.
`
