### ISSUE TITLE
Problem connecting due to permissions

### ISSUE THREAD

**Issue by hbldh** [mbientlab/MetaWear-SDK-Python#3]
I am having problems connecting due to some permission problem:
```python
Traceback (most recent call last):
  File "/home/hbldh/Repos/nmm/pymetawear/examples/accelerometer.py", line 23, in <module>
    c = MetaWearClient(str(address), debug=True)
  File "/home/hbldh/Repos/nmm/pymetawear/pymetawear/client.py", line 90, in __init__
    self.connect()
  File "/home/hbldh/Repos/nmm/pymetawear/pymetawear/client.py", line 125, in connect
    self.mw.connect()
  File "/home/hbldh/.virtualenvs/pymetawear-DTBsE4jA/lib/python3.5/site-packages/mbientlab/metawear/__init__.py", line 155, in connect
    self.gatt.connect(True, channel_type='random')
RuntimeError: Could not update HCI connection: Operation not permitted
```
The `wait=True` keyword requires elevated permissions on Ubuntu. I know this is not a RPi-problem, but it is easily remedied to make it usable on other platforms as well.

**Comment by scaryghost** [comment]
Accepted PR for this fix.
